# Generated by Django 6.1 on 2026-09-20 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenings/')),
                ('screening_date', models.DateTimeField(auto_now_add=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('quality_status', models.CharField(blank=True, max_length=30, null=True)),
                ('referable_probability', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=100, null=True)),
                ('classification_source', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('gradcam', models.CharField(blank=True, max_length=500, null=True)),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
